### PR TITLE
5 refactor send webhook function in the sender package for enhanced modularity error handling and logging

### LINKED ISSUE #5: Refactor SendWebhook function in the sender package for enhanced modularity, error handling, and logging
The SendWebhook function within the sender package, which is responsible for sending JSON POST requests to specified URLs, can benefit from several improvements:

- HTTP Client Initialization: Currently, a new `http.Client{`} is being instantiated every time the `SendWebhook` function is called. To make it efficient and reusable, we can consider initializing the client once and reusing it.

- Error Handling with Response Body: The code logs errors when it fails to close the response body but doesn't handle other potential issues that could arise with the response.

- Logging and Error Messages: The status log entry currently only logs "failed" or "delivered". It might be more informative to log more detailed messages, including the webhook ID and target URL for clarity. Additionally, returning just "failed" as an error doesn't provide much context on the issue.

- Refactoring for Testability: The code currently does multiple things - JSON marshaling, creating an HTTP request, sending the request, and handling the response. We should consider breaking this function into smaller functions for better unit testing and readability.

### PR DESCRIPTION
**Pull request by LewisYann**
Closes #5

### CODE REVIEW

File: webhook/sender/utils.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+		logging.WebhookLogger(logging.ErrorType, fmt.Errorf("error marshaling JSON: %s", err))
+		return nil, err
+	}
+	return jsonBytes, nil
+}
+
+func prepareRequest(url string, jsonBytes []byte, secretHash string) (*http.Request, error) {
+	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonBytes))
+	if err != nil {
+		logging.WebhookLogger(logging.WarningType, fmt.Errorf("error during the webhook request preparation"))
```
Comment (koladev32) [inline webhook/sender/utils.go:26]: This is an error. So we should use the `logging.ErrorType` constant

File: webhook/sender/utils.go [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+	"net/http"
+	"webhook/logging"
+)
+
+var HTTPClient = &http.Client{}
+
+func marshalJSON(data interface{}) ([]byte, error) {
+	jsonBytes, err := json.Marshal(data)
+	if err != nil {
+		logging.WebhookLogger(logging.ErrorType, fmt.Errorf("error marshaling JSON: %s", err))
```
Comment (koladev32) [inline webhook/sender/utils.go:17]: This is an error. So we should use the `logging.ErrorType` constant

File: webhook/sender/utils.go [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+func closeResponse(body io.ReadCloser) {
+	if err := body.Close(); err != nil {
+		logging.WebhookLogger(logging.WarningType, fmt.Errorf("error closing response body: %s", err))
+	}
+}
+
+func processResponse(resp *http.Response) (string, []byte, error) {
+	respBody, err := io.ReadAll(resp.Body)
+	if err != nil {
+		logging.WebhookLogger(logging.WarningType, fmt.Errorf("error reading response body: %s", err))
```
Comment (koladev32) [inline webhook/sender/utils.go:56]: This is an error. So we should use the `logging.ErrorType` constant.

File: webhook/sender/utils.go [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+	resp, err := HTTPClient.Do(req)
+	if err != nil {
+		return nil, err
+	}
+	return resp, nil
+}
+
+func closeResponse(body io.ReadCloser) {
+	if err := body.Close(); err != nil {
+		logging.WebhookLogger(logging.WarningType, fmt.Errorf("error closing response body: %s", err))
```
Comment (koladev32) [inline webhook/sender/utils.go:49]: This is an error. So we should use the `logging.ErrorType` constant.

File: webhook/sender/webhook.go [hunk 5]
```diff
@@ -1,56 +1,37 @@
...
-	// Determine the status based on the response code
-	status := "failed"
-	if resp.StatusCode == http.StatusOK {
-		status = "delivered"
-	}
-
-	log.Println(status)
 
 	if status == "failed" {
+		logging.WebhookLogger(logging.ErrorType, fmt.Errorf("webhook failed with status: %s, response body: %s", status, string(respBody)))
```
Comment (koladev32) [inline webhook/sender/webhook.go:34]: This is a warning. So we should use the `logging.WarningType` constant.

File: CHANGELOG.md [hunk 6]
```diff
@@ -14,4 +14,5 @@ and this project adheres to [Semantic Versioning](http://semver.org/).
 - Implement File Logging Module for Enhanced Error Handling (#7)
 - Refactor Subscribe function in the redis package for better error handling and modularity( #4 )
 - Improve Payload Flexibility to Accept Various JSON Formats( #1 )
-- Fix calculateBackoff redaclarring function (#16 )
\ No newline at end of file
+- Fix calculateBackoff redaclarring function (#16 )
+- Handle SendWebooks error and refact Sender package for more reusability ( [#5](https://github.com/koladev32/sendhooks-engine/issues/5) )
```
Comment (koladev32) [inline CHANGELOG.md:18]:
```suggestion
- Refactor SendWebhook function in the sender package for enhanced modularity, error handling, and logging ( #5 )
```

**Review by koladev32 — CHANGES_REQUESTED** [review]

**Review by koladev32 — APPROVED** [review]
